services:
  app:
    image: ghcr.io/ferilee/smakenpasofficial:latest
    container_name: smakenpasofficial
    ports:
      - "2005:2005"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 2005
      DATABASE_URL: /app/data/app.db
      UPLOAD_DIR: /app/uploads
    volumes:
      - sqlite_data:/app/data
      - upload_data:/app/uploads
    networks:
      - ferileenet

volumes:
  sqlite_data:
  upload_data:

networks:
  ferileenet:
    external: true
