services:
  app:
    image: ghcr.io/ferilee/smakenpasofficial:latest
    container_name: smakenpasofficial
    ports:
      - "2005:2005"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 2005
      DATABASE_URL: /app/data/app.db
      S3_ENDPOINT: http://global-storage:9000
      S3_PUBLIC_BASE_URL: https://s3.domain-anda.tld
      S3_BUCKET: smakenpasofficial-assets
      S3_REGION: us-east-1
      S3_FORCE_PATH_STYLE: "true"
    volumes:
      - sqlite_data:/app/data
    networks:
      - ferileenet

volumes:
  sqlite_data:

networks:
  ferileenet:
    external: true
